[package]
name = "ttyrecall-ebpf"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"

[dependencies]
aya-ebpf = "0.1.0"
aya-log-ebpf = "0.1.0"
ttyrecall-common = { path = "../ttyrecall-common" }

rustc-literal-escaper = { version = "0.0.2", features = ["rustc-dep-of-std"] } # For build-std=core, for proc_macro inside rust-src

# For build-std=core, for std inside rust-src
cfg-if = "=1.0.1"
hashbrown = { version = "=0.15.4", default-features = false, features = [
    'rustc-dep-of-std',
] }
rustc-demangle = { version = "=0.1.25", features = ['rustc-dep-of-std'] }
object = "=0.37.1"
dlmalloc = { version = "=0.2.9", features = ['rustc-dep-of-std'] }

[[bin]]
name = "ttyrecall"
path = "src/main.rs"

[features]
default = ["resource-saving"]
resource-saving = []

[profile.dev]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1
rpath = false

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
